services:
  frontend:
    container_name: goalManager-frontend
    image: node:lts
    working_dir: /app
    volumes:
      - ./frontend/:/app
    ports:
      - "8080:8080"
      - "24678:24678"
    entrypoint:
      - /bin/bash
      - -c
    command:
      - npm install && npm run dev
    stdin_open: true
    tty: true
  backend:
    container_name: goalManager-backend
    build: ./backend
    ports:
      - "3000:3000"
