services:
  frontend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./frontend/:/app
    ports:
      - "8080:8080"
      - "24678:24678"
    entrypoint:
      - /bin/bash
      - -c
    command:
      - npm install && npm run dev
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goalm
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
